// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenders.Data;
using Tenders.Models;

#nullable disable

namespace Tenders.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220322182309_UserWonTendersRemoveNullable")]
    partial class UserWonTendersRemoveNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Tenders.Models.Tender", b =>
                {
                    b.Property<int>("TenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExecutorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenderId");

                    b.HasIndex("ExecutorId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("Tenders.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TenderUser", b =>
                {
                    b.Property<int>("ParticipantsUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TendersWithParticipationTenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantsUserId", "TendersWithParticipationTenderId");

                    b.HasIndex("TendersWithParticipationTenderId");

                    b.ToTable("TenderUser");
                });

            modelBuilder.Entity("Tenders.Models.Tender", b =>
                {
                    b.HasOne("Tenders.Models.User", "Executor")
                        .WithMany("WonTenders")
                        .HasForeignKey("ExecutorId");

                    b.HasOne("Tenders.Models.User", "Organizer")
                        .WithMany("Tenders")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Executor");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("TenderUser", b =>
                {
                    b.HasOne("Tenders.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tenders.Models.Tender", null)
                        .WithMany()
                        .HasForeignKey("TendersWithParticipationTenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tenders.Models.User", b =>
                {
                    b.Navigation("Tenders");

                    b.Navigation("WonTenders");
                });
#pragma warning restore 612, 618
        }
    }
}
